config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "works#index"
  resources :works, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :work

  validates :text, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :work_tag_relations, dependent: :destroy
  has_many :works, through: :work_tag_relations

  validates :tag_name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true, length: { minimum: 2, maximum: 8 }

  has_many :works, dependent: :destroy
  has_many :comments
end

app/models/work.rb
class Work < ApplicationRecord
  has_many_attached :images
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :work_tag_relations, dependent: :destroy
  has_many :tags, through: :work_tag_relations


  def self.search(keyword)
    if keyword != ""
      Work.where('title LIKE ? OR description LIKE ?', "%#{keyword}%", "%#{keyword}%")
    else
      Work.all
    end
  end

end

app/models/work_tag.rb
class WorkTag
  include ActiveModel::Model
  attr_accessor :title, :description, :images, :tag_name, :user_id, :work_id, :tag_id

  with_options presence: true do
    validates :title
    validates :description
    validates :images
  end

  delegate :persisted?, to: :work

  def initialize(attributes = nil, work: Work.new, tag: Tag.new)
    @work = work
    @tag = tag
    attributes ||= default_attributes
    super(attributes)
  end
  
  def save
    work = Work.create(title: title, description: description, images: images, user_id: user_id)
    tag = Tag.find_or_create_by(tag_name: tag_name)
    WorkTagRelation.create(work: work, tag: tag)
  end

  def update(params)
    @work = Work.find(params[:work_id])
    work = @work.update(title: params[:title], description: params[:description], images: params[:images])
    @tag = @work.tags
    tag = @tag.find_or_create_by(tag_name: params[:tag_name])

    wtr = WorkTagRelation.where(work_id: work_id)
    wtr.update(work: work, tag: tag)
  end

  def to_model
    work
  end

  private

  attr_reader :work, :tag

  def default_attributes
    {
      title: work.title,
      description: work.description,
      images: work.images,
      tag_name: tag.tag_name,
      user_id: work.user_id
    }
  end

end

app/models/work_tag_relation.rb
class WorkTagRelation < ApplicationRecord
  belongs_to :work
  belongs_to :tag
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    comment = Comment.create(comment_params)
    @work = Work.find(params[:work_id])
    redirect_to  work_path(@work)
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, work_id: params[:work_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @nickname = @user.nickname
    @works = @user.works
  end

end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :find_work, only: [:show, :edit, :update]
  before_action :move_to_index, except: [:index, :show]

  def index
    @works = Work.all.order("created_at DESC")
  end

  def new
    @work_tag = WorkTag.new
  end

  def create
    @work_tag = WorkTag.new(work_params)
    if @work_tag.valid?
      @work_tag.save
    else
      render :new
    end
  end

  def show
    @work = Work.find(params[:id])
    @nickname = @work.user.nickname
    @comment = Comment.new
    @comments = @work.comments.includes(:user)
  end

  def edit
    @work_tag = WorkTag.new(work: @work)
  end

  def update
    if @work_tag = WorkTag.new.update(work_params)
      render :edit
    else
      redirect_to 
    end
  end

  def destroy
    work = Work.find(params[:id])
    work.destroy
  end

  def search
    @works = Work.search(params[:keyword])
  end

  private
  def work_params
    params.require(:work).permit(:title, :description, :tag_name, images: []).merge(user_id: current_user.id, work_id: params[:id])
  end

  def find_work
    @work = Work.find(params[:id])
    @tag = @work.tags
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/works_helper.rb
module WorksHelper
  def work_lists(works)
    html = ""
    works.each do |work|
      html += render(partial: "works", locals: {work: work})
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HachiApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="https://meyerweb.com/eric/tools/css/reset/reset200802.css">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<header>
  <div class="header_bar">
    <div id="header-left">
      <div class="header_title">
        <%= link_to 'Hachi App', root_path, class: "hachiapp" %>
      </div>
      <div class="header_menu">
        <ul class="menu_lists">
          <% if user_signed_in? %>
            <li><%= link_to "my page", user_path(current_user.id), class: "menu_list" %></li><span>|</span>
            <li><%= link_to "sign out", destroy_user_session_path, method: :delete, class: "menu_list" %></li><span>|</span>
            <li><%= link_to "new post", new_work_path, class:"menu_list" %></li>
          <% else %>
            <li><%= link_to "sign up", new_user_registration_path, class:"menu_list" %><br></li><span>|</span>
            <li><%= link_to "sign in", new_user_session_path, class:"menu_list" %></li>
          <% end %>
        </ul>
      </div>
    </div>
    <div id="header-right">
      <% if user_signed_in? %>
        <%= current_user.nickname %> さん
      <% else %>
        ゲスト さん
      <% end %>
    </div>
  </div>
</header>

<body>
  <%= yield %>
</body>

<footer>
  <p id="footer">
    &copy Hachi
  </p>
</footer>
  
</html>

app/views/users/show.html.erb
<div>
  <div class="user_page_title">
    <% if @user == current_user %>
      <div id="mypage">
        マイページ
        <ul class="mypage_menus">
          <li class="mypage_menu"><%= link_to '登録内容編集', edit_user_registration_path, class: "mypage_menu" %></li>
          <li class="mypage_menu"><%= link_to '退会', user_registration_path, method: :delete, class: "mypage_menu" %></li>
        </ul>
      </div>
      <div>
        <%= "自分の投稿一覧" %>
      </div>
    <% else %>
      <%= "#{@nickname}さんの投稿一覧"%>
    <% end %>
  </div>
  <div class="show_user_message">
    （クリックで詳細ページにとびます）
    </div>

  <div>
  <ul class="show_user_works">
    <% @works.each do |work| %>
      <% if work.images != 1 %>
        <% work.images.each do |w| %>
          <li><%= link_to image_tag(w, height:"250px"), work_path(w.record_id), class: "work_image" %></li>
        <% end %>
      <% else %>
          <li><%= link_to image_tag(work.images, height:"250px"), work_path(work.id), class: "work_image" %></li>
      <% end %>
    <% end %>
  </div>
  </ul>
</div>

<%= link_to '← トップへ戻る', root_path, class: "return_to" %>

app/views/works/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/works/_works.html.erb
<li class="work_list">
<div class="work-image">
  <%= link_to image_tag(work.images[0], height:"250px"), work_path(work.id) %>
</div>
<div class="work-info">
  <div class="work-title">
    <span class="work_title_font"><%= work.title %></span>
  </div>
</div>
</li>

app/views/works/create.html.erb
<div class="action-result">投稿が完了しました</div>

<%= link_to '← トップページへ戻る', root_path, class: "return_to" %>

app/views/works/destroy.html.erb
<div class="action-result">削除が完了しました</div>

<%= link_to '← トップページへ戻る', root_path, class: "return_to" %>

app/views/works/edit.html.erb
<div class="edit-post-title">
  投稿内容編集
</div>
<div class="edit-post-form">
<%= form_with model: @work_tag, class: "work_form", local: true do |f| %>
  <%= render 'error_messages', model: f.object %>
  <%= f.label :images, '画像を選択してください', class: "form_label" %>
  <%= f.file_field :images, multiple: true, class: "select_images" %><br>
  <%= f.text_field :title, placeholder: 'タイトルを入力してください', class: "title_input" %><br>
  <%= f.text_area :description, placeholder: '説明を入力してください', class: "description_input" %><br>
  <%= f.text_field :tag_name, placeholder: '登録したいタグを入力してください　例）#◯◯', class: "tag_input" %><br>
  <%= f.submit '投稿する' %>
<% end %>
</div>

<%= link_to '← 作品詳細へ戻る', work_path(@work.id), class: "return_to" %>

app/views/works/index.html.erb
<div class="works">
  <div class="work_table">
    作品一覧
  </div>
  <div class="search_form">
    <%= form_with(url: search_works_path, local: true, method: :get) do |f| %>
      <%= f.text_field :keyword, placeholder: 'キーワード検索', class: "search_input" %>
      <%= f.submit '検索', class: "search_btn" %>
    <% end %>
  </div>
  <div class="work_lists_field">
    <ul class="work_lists">
      <% @works.each do |work| %>
        <li class="work_list">
          <div class="work-image">
            <%= link_to image_tag(work.images[0], height:"250px"), work_path(work.id) %>
          </div>
          <div class="work-info">
            <div class="work-title">
              <span class="work_title_font"><%= work.title %></span>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/works/new.html.erb
<div class="new-post-title">
  新規投稿
</div>
<div class="new-post-form">
<%= form_with model: @work_tag, class: "work_form", local: true do |f| %>
  <%= render 'error_messages', model: f.object %>
  <%= f.label :images, '画像を選択してください', class: "form_label" %><br>
  <%= f.file_field :images, multiple: true, class: "select_images" %><br>
  <%= f.text_field :title, placeholder: 'タイトルを入力してください', class: "title_input" %><br>
  <%= f.text_area :description, placeholder: '説明を入力してください', class: "description_input" %><br>
  <%= f.text_field :tag_name, placeholder: '登録したいタグを入力してください　例）#◯◯', class: "tag_input" %><br>
  <%= f.submit '投稿する' %>
<% end %>
</div>

<%= link_to '← トップへ戻る', root_path, class: "return_to" %>

app/views/works/search.html.erb
<div class="action-result">
  検索結果
</div>
<div class="work_lists_field">
    <ul class="work_lists">
      <% @works.each do |work| %>
        <li class="work_list">
          <div class="work-image">
            <%= link_to image_tag(work.images[0], height:"250px"), work_path(work.id) %>
          </div>
          <div class="work-info">
            <div class="work-title">
              <span class="work_title_font"><%= work.title %></span>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
<%= link_to '← トップへ戻る', root_path, class: "return_to" %>

app/views/works/show.html.erb
<% if user_signed_in? && @work.user == current_user %>
  <div class="work_btn">
    <%= link_to '編集する', edit_work_path(@work.id) %>
    ｜
    <%= link_to '削除する', work_path(@work.id), method: :delete %>
  </div>
<% end %>

<div class="work-field">
  <div class="show-work-images">
    <% @work.images.each do |work| %>
      <li class="show-work-image">
        <%=image_tag work, height:"400px" %>
      </li>
    <% end %>
  </div>
  <div class="show-work-info">
    <div class="show-work-title">
      <%= @work.title %>
    </div>
    <div class="show-work-description">
      <%= @work.description %>
    </div>
    <div class="who-posted">
    by <%= link_to @nickname, user_path(@work.user), class:"user_name" %>
    </div>
  </div>
</div>

<div class="comment-field">
  <div class="show-comment">
    コメント一覧
  </div>
  <div class="comment-lists">
    <% if @comments.length >= 1 %>
      <% @comments.each do |comment| %>
        <div>
        <li class="comment-list">
          <div><%= link_to comment.user.nickname, user_path(comment.user), class: "comment_user_name" %></div>
          <div class="comment_text"><%= comment.text %></div>
        </li>
        </div>
      <% end %>
    <% else %>
      <div class="no_comment_message">まだコメントがありません</div>
    <% end %>
  </div>

  <div class="comment-form">
    <% if user_signed_in? %>
      <%= form_with(model: [@work, @comment], local: true) do |f| %>
        <%= f.text_area :text, placeholder: "write a comment", class:"text-form" %>
        <%= f.submit 'send', class:"send" %>
      <% end %>
    <% end %>
  </div>
</div>

<%= link_to "← トップへ戻る", root_path, class: "return_to" %>

app/views/works/update.html.erb
<div class="action-result">更新しました</div>

<%= link_to '← 作品詳細へ戻る', work_path(@work.id), class: "return_to" %>